-- Competitions context schema (T9.4, docs/process/t9-sprint-plan.md T9.4
-- section): competitions, competition_sessions, and competition_entries,
-- plus the DB-level WEIGHTED capacity guard that makes the entry invariant
-- real under concurrency.
--
-- 0014 is the next free number: 0013 was taken by T9.2
-- (0013_socialplay_entry_fee.sql), confirmed by listing db/migrations before
-- naming this file, per the ticket's instruction to renumber rather than
-- collide. (HANDOFF.md records the pre-existing duplicate-0005 pair as a
-- known, tolerated wart — this migration deliberately does not add a
-- second one.)
--
-- Prototype-only migration tooling: applied via docker-compose initdb.d on a
-- FRESH volume only (see CLAUDE.md gotchas) — after this lands, `make down`
-- (which drops the volume) then `make up`. Adopt golang-migrate/goose before
-- production.
--
-- host_id and player_id are plain text, not uuid FKs, for the same reason
-- games.host_id/registrations.player_id are (db/migrations/
-- 0005_socialplay.sql): there is no Users bounded context yet (HANDOFF.md),
-- so these are opaque identifiers until one exists.

CREATE TABLE competitions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    host_id             text NOT NULL,
    name                text NOT NULL,
    -- venue_facility_id is a REAL FK into the Facilities context, nullable,
    -- following T8.3's precedent for games (db/migrations/
    -- 0011_socialplay_facility_fk.sql). Nullable because a Competition's
    -- venue is optional by design: domain.Competition.VenueFacilityID's ""
    -- means "no known venue Facility yet", and
    -- app.Service.ScheduleCompetition skips the existence check entirely for
    -- it. Note Competitions gets the real FK from day one and never carries
    -- Social Play's opaque free-text facility_id column — there is no
    -- deprecated predecessor here to reconcile with.
    venue_facility_id   uuid REFERENCES facilities (id),
    capacity            integer NOT NULL CHECK (capacity > 0),
    -- guest_allowance is the maximum guests ONE entry may bring; 0 means no
    -- guests permitted. Distinct from capacity, which counts places.
    guest_allowance     integer NOT NULL DEFAULT 0 CHECK (guest_allowance >= 0),
    -- The closed enums below are text + CHECK (... IN (...)), mirroring the
    -- bookings.source precedent (db/migrations/0001_init.sql:25) rather than
    -- Postgres ENUM types, and listing exactly the value sets
    -- internal/competitions/domain declares. Keeping them in sync with the
    -- domain's own IsValid() methods is CLAUDE.md rule 4's dual enforcement
    -- applied to enums: the domain rejects a bad value in Go, the CHECK
    -- makes it unrepresentable in the database.
    --   payment_method <- domain.PaymentMethod (payment_method.go)
    --   format         <- domain.Format        (format.go)
    --   status         <- domain.Status        (competition.go)
    payment_method      text NOT NULL CHECK (payment_method IN ('online', 'cash', 'either')),
    format              text NOT NULL CHECK (format IN ('singles', 'doubles')),
    status              text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'cancelled')),
    -- entry_fee_cents/entry_fee_currency follow ADR-0005 (docs/adr/
    -- 0005-currency-code-column.md) and T9.2's games precedent exactly: an
    -- integer-minor-units amount always paired with its ISO 4217 code, never
    -- a bare cents value. A zero amount is a REAL value meaning a free
    -- competition, not "unset" — see domain.Money's doc comment. The CHECK
    -- is the Postgres half of domain.Money.Validate's negative-amount
    -- rejection; a negative entry fee would mean a Competition that pays its
    -- entrants, which is not a product this platform has.
    entry_fee_cents     bigint NOT NULL CHECK (entry_fee_cents >= 0),
    entry_fee_currency  text NOT NULL,
    -- share_token is the opaque token behind a Competition's shareable
    -- registration link (domain.Competition.ShareToken, generated by
    -- port.ShareTokenGenerator at scheduling time). UNIQUE because the token
    -- is what T9.5's share-link flow will resolve a Competition BY: two
    -- Competitions sharing a token would make that lookup ambiguous, and the
    -- constraint is what guarantees it can't happen rather than a convention
    -- the generator is trusted to uphold.
    --
    -- NOT NULL with no DEFAULT: every Competition gets a token at
    -- construction (see app.Service.ScheduleCompetition), so there is no
    -- back-fill path to keep open and no "tokenless Competition" state to
    -- define.
    share_token         text NOT NULL UNIQUE,
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX competitions_venue_facility_idx ON competitions (venue_facility_id);
CREATE INDEX competitions_status_idx ON competitions (status);

-- competition_sessions is the one structural difference from a Game: a
-- Competition "reserves courts across dates" (spec Flow 5), so where a Game
-- has a single (starts_at, ends_at, court_ids) triple on the games row
-- itself, a Competition has a LIST of them.
--
-- A child table rather than a repeated-array column, because a session is
-- three correlated values (start, end, courts) and Postgres has no way to
-- keep three parallel arrays aligned. Sessions remain a VALUE TYPE inside
-- the Competition aggregate (domain.Session has no identity and no
-- lifecycle) — the id column here is a storage key, not a domain identity,
-- and nothing outside this context ever addresses a session by it.
--
-- ON DELETE CASCADE because a session cannot outlive its Competition: it is
-- part of that aggregate, not an independent record.
--
-- court_ids is uuid[] for the same reason games.court_ids is (db/migrations/
-- 0005_socialplay.sql): Postgres can't express an array-element FK, so
-- referential integrity against courts is enforced at the application
-- boundary instead — internal/competitions/adapter/booking reserves each
-- court through the real Booking context, which validates the court as it
-- creates the underlying Booking.
--
-- position preserves the order the Host supplied the sessions in, so a
-- Competition round-trips through storage unchanged. Ordering by starts_at
-- alone would not be deterministic (two sessions on different courts may
-- share a start time), and a list that silently reorders itself between
-- write and read is the kind of low-grade wrongness that is very hard to
-- notice in a test written against a single-session fixture.
CREATE TABLE competition_sessions (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    competition_id  uuid NOT NULL REFERENCES competitions (id) ON DELETE CASCADE,
    position        integer NOT NULL CHECK (position >= 0),
    starts_at       timestamptz NOT NULL,
    ends_at         timestamptz NOT NULL,
    court_ids       uuid[] NOT NULL CHECK (cardinality(court_ids) > 0),
    CHECK (ends_at > starts_at),
    UNIQUE (competition_id, position)
);

CREATE INDEX competition_sessions_competition_idx ON competition_sessions (competition_id);

-- competition_entries is the Competitions analogue of registrations.
--
-- guest_count: each guest occupies a place exactly as the entrant does —
-- see the weighted capacity guard below, and domain.Enter's own rule. The
-- CHECK mirrors domain.Enter's guestCount < 0 rejection; the upper bound
-- (<= the owning Competition's guest_allowance) is NOT expressed here
-- because a CHECK constraint cannot reference another table. That check
-- lives in domain.Enter (ErrGuestAllowanceExceeded) and is a request-shape
-- validation rather than a concurrency-sensitive invariant: unlike capacity,
-- two simultaneous entries cannot combine to violate it, since it is a
-- property of one entry against one Competition's fixed allowance. So there
-- is no race for the database to close, and this is a deliberate scoping
-- decision rather than a gap.
--
--   source         <- domain.EntrySource   (entry.go): the same two values
--                     Social Play's RegistrationSource uses, per CLAUDE.md
--                     rule 7 and the sprint plan's §A3 ruling — NOT a third
--                     word like 'shared_link' for the same fact.
--   status         <- domain.EntryStatus   (entry.go)
--   payment_status <- domain.PaymentStatus (entry.go): three states, not
--                     two — "never paid" and "paid, then refunded" are
--                     different facts. T9 only ever writes the initial
--                     'unpaid'; Payments becomes its writer later (the same
--                     path Social Play took in T5.2 -> T6.5).
CREATE TABLE competition_entries (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    competition_id  uuid NOT NULL REFERENCES competitions (id) ON DELETE CASCADE,
    player_id       text NOT NULL,
    guest_count     integer NOT NULL DEFAULT 0 CHECK (guest_count >= 0),
    source          text NOT NULL DEFAULT 'app' CHECK (source IN ('app', 'social')),
    status          text NOT NULL DEFAULT 'entered' CHECK (status IN ('entered', 'cancelled')),
    payment_status  text NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid', 'paid', 'refunded')),
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX competition_entries_competition_idx ON competition_entries (competition_id);

-- The no-double-entry invariant (CLAUDE.md rule 4: enforced in Postgres AND
-- expressed in the domain — domain.Enter's ErrAlreadyEntered is the Go
-- half). A PARTIAL unique index, not a plain UNIQUE constraint, so a player
-- may enter again after cancelling: a cancelled row must not collide with a
-- new active one. Mirrors registrations_active_player_per_game_idx exactly
-- (db/migrations/0005_socialplay.sql). The adapter translates this index's
-- 23505 violation into domain.ErrAlreadyEntered rather than leaking it.
CREATE UNIQUE INDEX competition_entries_active_player_idx
    ON competition_entries (competition_id, player_id)
    WHERE status <> 'cancelled';

-- ===========================================================================
-- THE WEIGHTED CAPACITY GUARD
-- ===========================================================================
--
-- This is the invariant T9.4 exists to make real. domain.Enter already
-- refuses an entry whose weight would push a Competition past its capacity,
-- but that check reads a pre-insert snapshot: two requests that both read
-- "3 places free" will both decide they fit, and both insert. Only a check
-- that recomputes occupancy UNDER A ROW LOCK can close that window, which is
-- precisely the relationship domain.EnsureNoConflict has with bookings'
-- EXCLUDE constraint (CLAUDE.md rule 4) — the domain expresses the rule and
-- gives callers a clean error, the database enforces it.
--
-- WEIGHTED FROM DAY ONE, not retrofitted. T8.7 had to REWRITE Social Play's
-- capacity trigger because the original compared registration ROW COUNT
-- against capacity — which has no idea a row bringing 3 guests occupies 4
-- places, so up to `capacity` rows could land regardless of how many guests
-- each brought, silently overbooking a venue well past its real capacity
-- (see db/migrations/0012_socialplay_guest_capacity.sql's own doc comment).
-- That ticket paid the cost of discovering count-based triggers are wrong;
-- this one inherits the answer rather than rediscovering it, per T5's retro
-- finding 1. There has never been a count-based version of this function.
--
-- The two early-return branches are carried over unchanged from
-- enforce_game_capacity's T5.4-loop-2 shape (see db/migrations/
-- 0006_socialplay_capacity_guard.sql for their original derivation):
-- a row landing in or staying in 'cancelled' never consumes a place, and a
-- row that was already active before an UPDATE and stays active isn't
-- claiming a NEW place, so only INSERTs and cancelled->active UPDATEs reach
-- the actual check.
--
-- REQUIRED CONCURRENCY PROOF (CLAUDE.md rule 10, QA dossier §5 item 7): see
-- internal/competitions/adapter/postgres/capacity_concurrency_integration_test.go
-- — N simultaneous EnterCompetition calls with VARYING guest counts against
-- a Competition sized so exactly one combination fits, asserting the guard
-- admits exactly the set domain.Enter would. Run more than once, including a
-- cold start; a single green run is not evidence. The T9.4 PR description
-- states plainly which environment actually executed that proof.
CREATE FUNCTION enforce_competition_capacity() RETURNS trigger AS $$
DECLARE
    competition_capacity integer;
    active_weight        integer;
    new_weight           integer;
BEGIN
    -- A row landing in (or staying in) 'cancelled' never occupies a place.
    IF NEW.status = 'cancelled' THEN
        RETURN NEW;
    END IF;

    -- A row already active before this UPDATE that stays active (e.g. a
    -- future payment_status-only write) isn't claiming a new place — skip.
    -- Only INSERTs and cancelled->active UPDATEs reach the check below.
    IF TG_OP = 'UPDATE' AND OLD.status <> 'cancelled' THEN
        RETURN NEW;
    END IF;

    -- THE ACTUAL RACE FIX. Locking the owning competitions row serializes
    -- every concurrent entry for the same competition_id here, so the sum
    -- below always runs against a state reflecting every earlier-committed
    -- entry rather than a stale snapshot. The weighted sum that follows is
    -- what makes the answer CORRECT; this lock is what makes it SAFE.
    -- Neither alone is sufficient.
    SELECT capacity INTO competition_capacity
    FROM competitions
    WHERE id = NEW.competition_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'competitions: competition % not found', NEW.competition_id
            USING ERRCODE = 'foreign_key_violation';
    END IF;

    -- Weighted occupancy of every OTHER active entry: each occupies
    -- (1 + its own guest_count) places, mirroring domain.SpotsLeft and
    -- domain.Enter's countActiveEntries exactly. A plain COUNT(*) here
    -- undercounts every row with guest_count > 0 — the exact bug T8.7 had to
    -- go back and fix in Social Play.
    SELECT COALESCE(SUM(1 + guest_count), 0) INTO active_weight
    FROM competition_entries
    WHERE competition_id = NEW.competition_id
      AND status <> 'cancelled'
      AND id <> NEW.id;

    -- NEW occupies its entrant's place plus one per guest — it does not
    -- always weigh exactly 1, which is the whole reason a row count is the
    -- wrong quantity to compare.
    new_weight := 1 + NEW.guest_count;

    IF active_weight + new_weight > competition_capacity THEN
        RAISE EXCEPTION 'competitions: competition % is at capacity (%/%, incl. guests)',
            NEW.competition_id, active_weight + new_weight, competition_capacity
            USING ERRCODE = 'P0001';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- BEFORE (not AFTER) so a rejected entry never becomes a row at all, and
-- FOR EACH ROW so a multi-row INSERT is checked entry by entry.
-- internal/competitions/adapter/postgres translates the P0001 raised above
-- into domain.ErrCompetitionFull — the same sentinel domain.Enter's own
-- pre-check returns, so callers see ONE error type no matter which layer
-- caught the conflict (CLAUDE.md rule 5: no new error type reaches the
-- wire).
CREATE TRIGGER competition_entries_capacity_guard
    BEFORE INSERT OR UPDATE ON competition_entries
    FOR EACH ROW EXECUTE FUNCTION enforce_competition_capacity();
