// Package postgres is the Payments context's Postgres adapter. It
// implements port.Repository against sqlc-generated queries and translates
// Postgres errors into domain errors — CLAUDE.md rule 5. It only compiles
// after `make generate` has produced internal/gen/paymentsdb (see
// CLAUDE.md gotchas); that package is gitignored and not committed.
package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/nhuthuynh/white-label/internal/payments/domain"

	paymentsdb "github.com/nhuthuynh/white-label/internal/gen/paymentsdb"
)

// pgUniqueViolation is the Postgres error code payments_payable_unique_idx
// (db/migrations/0005_payments.sql) raises on a second Payment for the
// same (payable_type, payable_id) — a distinctness race, closed by a plain
// unique index (T5 LESSONS.md finding), not a locking trigger.
const pgUniqueViolation = "23505"

type Repository struct {
	q *paymentsdb.Queries
}

func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{q: paymentsdb.New(pool)}
}

func (r *Repository) Create(ctx context.Context, p domain.Payment) (domain.Payment, error) {
	row, err := r.q.CreatePayment(ctx, paymentsdb.CreatePaymentParams{
		ID:               mustUUID(p.ID),
		PayableType:      string(p.PayableType),
		PayableID:        mustUUID(p.PayableID),
		AmountCents:      p.Amount.Cents,
		CurrencyCode:     p.Amount.Currency,
		Method:           string(p.Method),
		Status:           string(p.Status),
		StripeReference:  toText(p.StripeReference),
		RecordedByUserID: toText(p.RecordedByUserID),
	})
	if err != nil {
		return domain.Payment{}, translateErr(err)
	}
	return fromFields(row.ID, row.PayableType, row.PayableID, row.AmountCents, row.CurrencyCode, row.Method, row.Status, row.StripeReference, row.RecordedByUserID), nil
}

func (r *Repository) GetByID(ctx context.Context, id string) (domain.Payment, error) {
	row, err := r.q.GetPaymentByID(ctx, mustUUID(id))
	if err != nil {
		return domain.Payment{}, translateErr(err)
	}
	return fromFields(row.ID, row.PayableType, row.PayableID, row.AmountCents, row.CurrencyCode, row.Method, row.Status, row.StripeReference, row.RecordedByUserID), nil
}

// GetByStripeReference implements port.Repository (T18.1, closes #167).
func (r *Repository) GetByStripeReference(ctx context.Context, ref string) (domain.Payment, error) {
	row, err := r.q.GetPaymentByStripeReference(ctx, toText(ref))
	if err != nil {
		return domain.Payment{}, translateErr(err)
	}
	return fromFields(row.ID, row.PayableType, row.PayableID, row.AmountCents, row.CurrencyCode, row.Method, row.Status, row.StripeReference, row.RecordedByUserID), nil
}

func (r *Repository) Update(ctx context.Context, p domain.Payment) (domain.Payment, error) {
	row, err := r.q.UpdatePayment(ctx, paymentsdb.UpdatePaymentParams{
		ID:              mustUUID(p.ID),
		Status:          string(p.Status),
		StripeReference: toText(p.StripeReference),
	})
	if err != nil {
		return domain.Payment{}, translateErr(err)
	}
	return fromFields(row.ID, row.PayableType, row.PayableID, row.AmountCents, row.CurrencyCode, row.Method, row.Status, row.StripeReference, row.RecordedByUserID), nil
}

// translateErr maps infrastructure failures onto domain errors — the only
// errors allowed to cross out of this package (CLAUDE.md rule 5).
func translateErr(err error) error {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == pgUniqueViolation {
		return domain.ErrPaymentAlreadyRecorded
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.ErrPaymentNotFound
	}
	return fmt.Errorf("payments postgres adapter: %w", err)
}

// fromFields builds a domain.Payment from the 9 columns every payments
// query selects. sqlc generates a distinct Row struct per query
// (CreatePaymentRow, GetPaymentByIDRow, UpdatePaymentRow, ...) rather than
// reusing the paymentsdb.Payment table model (which also carries
// created_at/updated_at, not selected by any query) — see the CLAUDE.md
// gotcha on why, and internal/booking/adapter/postgres's identical
// fromFields for the established pattern. A shared field-level converter
// avoids duplicating this mapping three times.
func fromFields(id pgtype.UUID, payableType string, payableID pgtype.UUID, amountCents int64, currencyCode, method, status string, stripeReference, recordedByUserID pgtype.Text) domain.Payment {
	return domain.Payment{
		ID:          id.String(),
		PayableType: domain.PayableType(payableType),
		PayableID:   payableID.String(),
		Amount: domain.Money{
			Cents:    amountCents,
			Currency: currencyCode,
		},
		Method:           domain.Method(method),
		Status:           domain.Status(status),
		StripeReference:  stripeReference.String,
		RecordedByUserID: recordedByUserID.String,
	}
}

func mustUUID(s string) pgtype.UUID {
	var u pgtype.UUID
	if err := u.Scan(s); err != nil {
		// Payment IDs are generated by port.IDGenerator (adapter/idgen) as
		// UUIDs; payable IDs are Booking/Registration ids, also UUIDs — a
		// malformed value here means an upstream invariant was already
		// violated, which is a programmer error, not a runtime one.
		// Mirrors internal/booking/adapter/postgres's identical helper.
		panic(fmt.Sprintf("payments postgres adapter: invalid uuid %q: %v", s, err))
	}
	return u
}

func toText(s string) pgtype.Text {
	return pgtype.Text{String: s, Valid: s != ""}
}
