// Package postgres is the Booking context's Postgres adapter. It implements
// port.Repository against sqlc-generated queries and translates Postgres
// errors into domain errors — CLAUDE.md rule 5. It only compiles after
// `make generate` has produced internal/gen/bookingdb (see CLAUDE.md
// gotchas); that package is gitignored and not committed.
package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/nhuthuynh/white-label/internal/booking/domain"
	bookingdb "github.com/nhuthuynh/white-label/internal/gen/bookingdb"
)

// pgExclusionViolation is Postgres error code 23P01, raised by the
// bookings.no_overlap-equivalent EXCLUDE constraint (db/migrations/0001_init.sql).
const pgExclusionViolation = "23P01"

type Repository struct {
	q *bookingdb.Queries
}

func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{q: bookingdb.New(pool)}
}

func (r *Repository) Create(ctx context.Context, b domain.Booking) (domain.Booking, error) {
	row, err := r.q.CreateBooking(ctx, bookingdb.CreateBookingParams{
		ID:          mustUUID(b.ID),
		CourtID:     mustUUID(b.CourtID),
		Source:      string(b.Source),
		Status:      string(b.Status),
		StartsAt:    toTimestamptz(b.Range.Start),
		EndsAt:      toTimestamptz(b.Range.End),
		ReferenceID: toText(b.ReferenceID),
	})
	if err != nil {
		return domain.Booking{}, translateErr(err)
	}
	return fromFields(row.ID, row.CourtID, row.Source, row.Status, row.StartsAt, row.EndsAt, row.ReferenceID), nil
}

func (r *Repository) ListActiveForCourt(ctx context.Context, courtID string, rng domain.TimeRange) ([]domain.Booking, error) {
	rows, err := r.q.ListActiveForCourt(ctx, bookingdb.ListActiveForCourtParams{
		CourtID: mustUUID(courtID),
		FromTs:  toTimestamptz(rng.Start),
		ToTs:    toTimestamptz(rng.End),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]domain.Booking, 0, len(rows))
	for _, row := range rows {
		out = append(out, fromFields(row.ID, row.CourtID, row.Source, row.Status, row.StartsAt, row.EndsAt, row.ReferenceID))
	}
	return out, nil
}

func (r *Repository) GetByID(ctx context.Context, id string) (domain.Booking, error) {
	row, err := r.q.GetBookingByID(ctx, mustUUID(id))
	if err != nil {
		return domain.Booking{}, translateErr(err)
	}
	return fromFields(row.ID, row.CourtID, row.Source, row.Status, row.StartsAt, row.EndsAt, row.ReferenceID), nil
}

func (r *Repository) Update(ctx context.Context, b domain.Booking) (domain.Booking, error) {
	row, err := r.q.UpdateBookingStatus(ctx, bookingdb.UpdateBookingStatusParams{
		ID:     mustUUID(b.ID),
		Status: string(b.Status),
	})
	if err != nil {
		return domain.Booking{}, translateErr(err)
	}
	return fromFields(row.ID, row.CourtID, row.Source, row.Status, row.StartsAt, row.EndsAt, row.ReferenceID), nil
}

// translateErr maps infrastructure failures onto domain errors — the only
// errors allowed to cross out of this package (CLAUDE.md rule 5).
func translateErr(err error) error {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == pgExclusionViolation {
		return domain.ErrCourtDoubleBooked
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.ErrBookingNotFound
	}
	return fmt.Errorf("booking postgres adapter: %w", err)
}

// fromFields builds a domain.Booking from the 7 columns every booking query
// selects. sqlc generates a distinct Row struct per query (CreateBookingRow,
// ListActiveForCourtRow, ...) rather than reusing the bookingdb.Booking table
// model, because none of the queries select the generated `during` column —
// see the CLAUDE.md gotcha on why they can't. A shared field-level converter
// avoids duplicating this mapping four times.
func fromFields(id, courtID pgtype.UUID, source, status string, startsAt, endsAt pgtype.Timestamptz, referenceID pgtype.Text) domain.Booking {
	return domain.Booking{
		ID:      id.String(),
		CourtID: courtID.String(),
		Source:  domain.Source(source),
		Status:  domain.Status(status),
		Range: domain.TimeRange{
			Start: startsAt.Time,
			End:   endsAt.Time,
		},
		ReferenceID: referenceID.String,
	}
}

func mustUUID(s string) pgtype.UUID {
	var u pgtype.UUID
	if err := u.Scan(s); err != nil {
		// Booking IDs are generated by port.IDGenerator (adapter/idgen) as
		// UUIDs; a malformed ID here means an upstream invariant was
		// already violated, which is a programmer error, not a runtime one.
		panic(fmt.Sprintf("booking postgres adapter: invalid uuid %q: %v", s, err))
	}
	return u
}

func toTimestamptz(t time.Time) pgtype.Timestamptz {
	return pgtype.Timestamptz{Time: t, Valid: true}
}

func toText(s string) pgtype.Text {
	return pgtype.Text{String: s, Valid: s != ""}
}
